spring:
  jpa.show-sql: true
  jpa.hibernate.use-new-id-generator-mappings: false
  datasource.url: jdbc:mysql://localhost:3306/sso?createDatabaseIfNotExist=true
  datasource.username: root
  datasource.password: 12345678
  main:
    allow-bean-definition-overriding: true
  liquibase:
    change-log: db/kgs-changelog.yml
    drop-first: true
server:
  port: 9988
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
        internal:
          InstanceMetadataServiceResourceFetcher: error
