spring:
  jpa.show-sql: true
  jpa.hibernate.use-new-id-generator-mappings: false
  datasource.driver-class-name: com.mysql.cj.jdbc.Driver
  datasource.url: jdbc:mysql://kgs-database.cbdv4cgnmeky.eu-north-1.rds.amazonaws.com/kgs?createDatabaseIfNotExist=true
  datasource.username: root
  datasource.password: 12345678
  main:
    allow-bean-definition-overriding: true
  liquibase:
    change-log: db/kgs-changelog.yml
server:
  port: 8877
logging:
  level:
    root: info
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
        internal:
          InstanceMetadataServiceResourceFetcher: error
